import { PERMISSION, type Permission } from "./permissions";

export const ROLE = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  MANAGER: "Manager",
  VIEWER: "Viewer",
} as const;

export type RoleName = (typeof ROLE)[keyof typeof ROLE];

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  [ROLE.SUPER_ADMIN]: Object.values(PERMISSION),
  [ROLE.ADMIN]: Object.values(PERMISSION),
  [ROLE.MANAGER]: [
    PERMISSION.DASHBOARD_VIEW,
    PERMISSION.USER_READ,
    PERMISSION.ROLE_READ,
    PERMISSION.PROJECT_CREATE,
    PERMISSION.PROJECT_READ,
    PERMISSION.PROJECT_UPDATE,
    PERMISSION.INDICATOR_CREATE,
    PERMISSION.INDICATOR_READ,
    PERMISSION.INDICATOR_UPDATE,
    PERMISSION.DATA_COLLECT,
    PERMISSION.DATA_READ,
    PERMISSION.DATA_UPDATE,
    PERMISSION.REPORT_GENERATE,
    PERMISSION.REPORT_READ,
    PERMISSION.REPORT_EXPORT,
    PERMISSION.EVALUATION_CREATE,
    PERMISSION.EVALUATION_READ,
    PERMISSION.EVALUATION_UPDATE,
  ],
  [ROLE.VIEWER]: [
    PERMISSION.DASHBOARD_VIEW,
    PERMISSION.USER_READ,
    PERMISSION.ROLE_READ,
    PERMISSION.PROJECT_READ,
    PERMISSION.INDICATOR_READ,
    PERMISSION.DATA_READ,
    PERMISSION.REPORT_READ,
    PERMISSION.EVALUATION_READ,
  ],
};

export const SYSTEM_ROLES: RoleName[] = [ROLE.SUPER_ADMIN, ROLE.ADMIN];
