export const AUDIT_ACTION = {
  // ─── Auth ───────────────────────────────────────────────
  LOGIN: "AUTH_LOGIN",
  LOGOUT: "AUTH_LOGOUT",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  TOKEN_REFRESHED: "AUTH_TOKEN_REFRESHED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",

  // ─── Users ──────────────────────────────────────────────
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

  // ─── Roles & Permissions ────────────────────────────────
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  PERMISSION_ASSIGNED: "PERMISSION_ASSIGNED",
  PERMISSION_REVOKED: "PERMISSION_REVOKED",

  // ─── Organization ───────────────────────────────────────
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_DELETED: "ORG_DELETED",
  ORG_SETTINGS_UPDATED: "ORG_SETTINGS_UPDATED",

  // ─── Projects ───────────────────────────────────────────
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED",
  PROJECT_TEAM_ASSIGNED: "PROJECT_TEAM_ASSIGNED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  PROJECT_DELETED: "PROJECT_DELETED",

  // ─── Results Framework ──────────────────────────────────
  LOGFRAME_CREATED: "LOGFRAME_CREATED",
  LOGFRAME_UPDATED: "LOGFRAME_UPDATED",
  LOGFRAME_DELETED: "LOGFRAME_DELETED",
  VERSION_APPROVED: "VERSION_APPROVED",
  GOAL_CREATED: "GOAL_CREATED",
  OUTCOME_CREATED: "OUTCOME_CREATED",
  OUTPUT_CREATED: "OUTPUT_CREATED",
  ASSUMPTION_CREATED: "ASSUMPTION_CREATED",
  RISK_CREATED: "RISK_CREATED",

  // ─── Indicators ─────────────────────────────────────────
  INDICATOR_CREATED: "INDICATOR_CREATED",
  INDICATOR_UPDATED: "INDICATOR_UPDATED",
  INDICATOR_ARCHIVED: "INDICATOR_ARCHIVED",
  INDICATOR_DELETED: "INDICATOR_DELETED",
  BASELINE_CREATED: "BASELINE_CREATED",
  TARGET_CREATED: "TARGET_CREATED",
  DISAGGREGATION_CREATED: "DISAGGREGATION_CREATED",
  MOV_CREATED: "MOV_CREATED",

  // ─── System ─────────────────────────────────────────────
  SYSTEM_INITIALIZED: "SYSTEM_INITIALIZED",
  SYSTEM_CONFIGURED: "SYSTEM_CONFIGURED",
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
